routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('posts', 'PostsController');

Route::resource('pages', 'PagesController');

Route::resource('content_terms', 'ContentTermsController', ['except' => ['show']]);

Route::get('languages/{id}/set', ['as' => 'languages.set', 'uses' => 'LanguagesController@set']);
Route::resource('languages', 'LanguagesController', ['except' => ['show']]);

Route::resource('layout_categories', 'LayoutCategoriesController', ['except' => ['show']]);

Route::resource('layout_items', 'LayoutItemsController', ['except' => ['show']]);

Route::get('layout_item_translates/create/{encrypted_id}', ['as' => 'layout_item_translates.create', 'uses' => 'LayoutItemTranslatesController@create']);
Route::resource('layout_item_translates', 'LayoutItemTranslatesController', ['except' => ['create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_roles', 'UserRolesController', ['except' => ['show']]);

Route::get('user_privileges/create/{encrypted_id}', ['as' => 'user_privileges.create', 'uses' => 'UserPrivilegesController@create']);
Route::resource('user_privileges', 'UserPrivilegesController', ['except' => ['create', 'show', 'edit', 'destroy']]);

Route::resource('profiles', 'ProfilesController', ['only' => ['edit', 'update']]);

Route::resource('user_accounts', 'UserAccountsController', ['except' => ['show']]);

Route::resource('user_metas', 'UserMetasController', ['except' => ['index', 'create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_passwords', 'UserPasswordsController', ['only' => ['update']]);

Route::resource('privileges', 'PrivilegesController', ['except' => ['show']]);

// Static Ajax routes ;
Route::prefix('ajax')->group(function () {
	Route::post('of_taxonomy', ['as' => 'ajax.of_taxonomy', 'uses' => 'AjaxController@of_taxonomy']);
	Route::post('realtime_upload', ['as' => 'ajax.realtime_upload', 'uses' => 'AjaxController@realtime_upload']);
});

app/ContentTerms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ContentTerms extends Model
{
	public $timestamps = false;

    protected $fillable = [
    	'slug',
    	'title',
    ];

    public static function terms_by($where =['taxonomy' => 'label'])
    {
        $cols_terms = Schema::getColumnListing('content_terms');
        $cols_taxonomy = Schema::getColumnListing('content_taxonomy');

    	$terms = DB::table('content_terms')
                    ->select(
                        'content_terms.*',
                        'content_taxonomy.taxonomy',
                        'content_taxonomy.parent as parent'
                    )
                    ->join('content_taxonomy', function($join) use ($where, $cols_taxonomy) {

                        $join->on('content_terms.term_id', '=', 'content_taxonomy.term_id');

                        if(in_array(key($where), $cols_taxonomy))
                        	$join->where('content_taxonomy.'. key($where), '=', $where[key($where)]);
                    })
                    ->where(function($query) use ($where, $cols_terms) {

                        if(in_array(key($where), $cols_terms))
                            $query->where('content_terms.'. key($where), '=', $where[key($where)]);
                    })
                    ->orderBy('content_terms.title', 'asc')
                    ->get();

	    return $terms;
    }

    public static function opt_by($where =['taxonomy' => 'label'])
    {
        $terms = self::terms_by($where);

        $str_opt = '';

        if(!is_null($terms))
        {
            foreach ($terms as $term)
            {
                $str_opt .='<option value="'. $term->term_id .'">'. $term->title .'</option>';
            }
        }

        return $str_opt;
    }
}

app/Http/Controllers/ContentTermsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Session;

use App\ContentTaxonomy;
use App\ContentTerms;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Input;

class ContentTermsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->authorized('content_terms')) {
            abort(403, 'Unauthorized action.');
        }

        $display = Input::has('display') ? Input::get('display') :7;

        $content_terms = DB::table('content_terms')
                            ->select(
                                'content_terms.*',
                                'content_taxonomy.taxonomy',
                                'content_taxonomy.parent as parent'
                            )
                            ->join('content_taxonomy', function($join) {
                                $join->on('content_terms.term_id', '=', 'content_taxonomy.term_id');
                            })
                            ->orderBy('content_terms.term_id', 'desc')
                            ->paginate($display);

        return view('content_terms.index', compact(['content_terms', 'display']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::user()->authorized('create_content_term')) {
            abort(403, 'Unauthorized action.');
        }

        $taxonomies = DB::table('content_taxonomy')
                            ->distinct()
                            ->get(['taxonomy']);

        $terms = DB::table('content_terms')
                    ->select('content_terms.*')
                    ->get();

        return view('content_terms.create', compact(['taxonomies', 'terms']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!Auth::user()->authorized('create_content_term')) {
            abort(403, 'Unauthorized action.');
        }

        $required_taxonomy = 'required';
        $required_new_taxonomy = 'nullable';

        if($request->has('new_taxonomy'))
        {
            $required_taxonomy = 'nullable';
            $required_new_taxonomy = 'required|max:191|regex:/^[0-9a-z_]+$/';
        }


        $validator = Validator::make($request->all(), [
                'taxonomy' => $required_taxonomy,
                'new_taxonomy' => $required_new_taxonomy,
                'slug' => 'required|regex:/^[0-9a-z_]+$/|max:100|unique:content_terms',
                'title' => 'required|max:512',
                'term_group' => 'nullable|numeric',
            ]);

        if($validator->fails()) {
            return redirect()->back()
                        ->withInput()
                        ->withErrors($validator);
        }

        $term = new ContentTerms([
                        'slug' => $request->input('slug'),
                        'title' => $request->input('title'),
                        'term_group' => $request->input('term_group'),
                    ]);

        $term->save();

        // get existed taxonomy, Or use new one
        $_taxonomy = $request->has('new_taxonomy') ? $request->input('new_taxonomy') : $request->input('taxonomy');

        $taxonomy = new ContentTaxonomy([
                'term_id' => $term->id,
                'taxonomy' => strtolower($_taxonomy),
                'description' => $request->input('description'),
                'parent' => $request->input('parent'),
            ]);

        $taxonomy->save();

        // check if has meta -;
        if($request->has('term_meta'))
        {
            $qtm = array();
            foreach ($request->input('term_meta') as $key => $value) {
                $jd = json_decode($value);
                $qtm[key($jd)] = $jd->{key($jd)};
            }

            \Helper::store_meta('content_termmeta', ['term_id' => $term->id], $qtm, [], false);
        }

        Session::flash('inserted', 'New term is inserted');

        if($request->has('sane'))
            return redirect('content_terms/create');

        return redirect('content_terms');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ContentTerms  $contentTerms
     * @return \Illuminate\Http\Response
     */
    public function edit($encrypted_id)
    {
        if(!Auth::user()->authorized('update_content_term')) {
            abort(403, 'Unauthorized action.');
        }

        $decrypted_id = decrypt($encrypted_id);

        $taxonomies = DB::table('content_taxonomy')
                            ->distinct()
                            ->get(['taxonomy']);

        $terms = DB::table('content_terms')
                    ->select('content_terms.*')
                    ->get();

        // taxonomy of this term ;
        $tt = DB::table('content_taxonomy')
                        ->where('term_id', $decrypted_id)
                        ->first();

        $term = ContentTerms::where('term_id', $decrypted_id)->first();

        $meta = DB::table('content_termmeta')->where('term_id', $decrypted_id)->get()->toArray();

        $str_meta ='';

        if(count($meta) !=0)
        {
            foreach ($meta as $key => $value) {

                $merged = '{"'. $value->meta_key .'" : "'. $value->meta_value .'"}';

                $str_meta .="<section class='col col-6 flexibled-error ofmeta'>
                                    <label class='label'>
                                        &mdash;/. Term meta <code>*</code> <i class='glyphicon glyphicon-qrcode font-12'></i>
                                        <a href='javascript:;' class='btn btn-xs rollback-meta txt-color-red' data-cfm='true'>Clear</a>
                                        <div class='inline-block' id='for-term_meta[]'></div>
                                    </label>
                                    <label class='input'>
                                        <input type='text' name='term_meta[]' class='flexibled border-0 border-bottom-1 font-bold'
                                            value='". $merged ."' placeholder='{\"meta_key\" : \"meta_value\"}' />
                                    </label>
                                </section>";
            }
        }

        return view('content_terms.edit', compact(['taxonomies', 'terms', 'tt', 'term', 'meta', 'str_meta']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ContentTerms  $contentTerms
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $encrypted_id)
    {
        if(!Auth::user()->authorized('update_content_term')) {
            abort(403, 'Unauthorized action.');
        }

        $decrypted_id = decrypt($encrypted_id);

        $validator = Validator::make($request->all(), [
                'taxonomy' => 'required',
                'slug' => "required|regex:/^[0-9a-z_]+$/|max:100|unique:content_terms,slug,{$decrypted_id},term_id",
                'title' => 'required|max:512',
                'term_group' => 'nullable|numeric',
            ]);

        if($validator->fails()) {
            return redirect()->back()
                        ->withInput()
                        ->withErrors($validator);
        }

        DB::table('content_terms')
            ->where('term_id', $decrypted_id)
            ->update([
                'slug' => $request->input('slug'),
                'title' => $request->input('title'),
                'term_group' => $request->input('term_group'),
            ]);

        DB::table('content_taxonomy')
            ->where('term_id', $decrypted_id)
            ->update([
                'taxonomy' => $request->input('taxonomy'),
                'description' => $request->input('description'),
                'parent' => $request->input('parent'),
            ]);

        // check if has meta ;

        $qtm = array();

        if($request->has('term_meta'))
        {
            foreach ($request->input('term_meta') as $key => $value)
            {
                if(!is_null($value))
                {
                    $jd = json_decode($value);

                    if($jd !=null)
                    {
                        $qtm[key($jd)] = $jd->{key($jd)};
                    }
                }
            }
        }

        \Helper::store_meta('content_termmeta', ['term_id' => $decrypted_id], $qtm, [], false);

        Session::flash('updated', 'Content term is updated');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ContentTerms  $contentTerms
     * @return \Illuminate\Http\Response
     */
    public function destroy($encrypted_id)
    {
        if(!Auth::user()->authorized('delete_content_term')) {
            abort(403, 'Unauthorized action.');
        }

        $decrypted_id = decrypt($encrypted_id);

        $term = DB::table('content_terms')->where('term_id', $decrypted_id)->limit(1);
        $term->delete();

        $taxonomy = DB::table('content_taxonomy')->where('term_id', $decrypted_id)->limit(1);
        $taxonomy->delete();

        $meta = DB::table('content_termmeta')->where('term_id', $decrypted_id);
        $meta->delete();

        Session::flash('deleted', "Content term is deleted");

        return redirect('content_terms');
    }
}

resources/views/content_terms/create.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->create_content_term->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-8">

							<form action="{{ route('content_terms.index') }}" class="smart-form" method="post">

								<fieldset>

									<div class="row">
									@if(Session::has('inserted'))
										<section class="col col-6">
											{!! Helper::alert('success', Session::get('inserted'), 'block font-15') !!}
										</section>
									@endif
									</div>

									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Taxonomy <code>*</code>

												@if($errors->has('taxonomy'))
													<div class="error-badge" id="for-taxonomy">
														{!! Helper::alert('danger', $errors->first('taxonomy')) !!}
													</div>
												@endif
											</label>
											<label class="select">
												<select class="input-sm border-0 border-bottom-1" name="taxonomy">

													{!! Helper::empty_option() !!}

													@foreach($taxonomies as $taxonomy)

														@if(old('taxonomy') ==$taxonomy->taxonomy)
															<option value="{{ $taxonomy->taxonomy }}" selected>{{ $taxonomy->taxonomy }}</option>
														@else
															<option value="{{ $taxonomy->taxonomy }}">{{ $taxonomy->taxonomy }}</option>
														@endif
													@endforeach
												</select><i></i>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												<span class="txt-color-blue">
													Don't has taxonomy!
												</span>

												@if($errors->has('new_taxonomy'))
													<div class="error-badge" id="for-new_taxonomy">
														{!! Helper::alert('danger', $errors->first('new_taxonomy')) !!}
													</div>
												@endif
											</label>
											<label class="toggle txt-color-red">
												<input name="onoff" class="onoff" data-target="new_taxonomy" type="checkbox" {!! old('onoff') ? 'checked' :'' !!}>
												<i data-swchon-text="ON" data-swchoff-text="OFF"></i> Create one →
											</label>
										</section>
									</div>
									<div class="row onoff_input {!! old('onoff') ? '' :'hidden' !!}">
										<section class="col col-6 flexibled-error">
											<label class="input">
												<input type="text" {!! old('onoff') ? 'name="new_taxonomy"' :'tmp-name="new_taxonomy"' !!}
													value="{{ old('new_taxonomy') }}" class="input-sm border-0 border-bottom-1">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error atoslug-upper">
											<label class="label">
												Slug <botton class="btn btn-xs btn-primary atoslug" data-target="slug" data-slugof="term">auto</botton>

												@if($errors->has('slug'))
													<div class="error-badge" id="for-slug">
														{!! Helper::alert('danger', $errors->first('slug')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="slug" value="{{ old('slug') }}" class="input-sm border-0 border-bottom-1">
											</label>
											<div class="note">
												{!! $layout->label->slug_note->title !!}
											</div>
										</section>
									</div>
									<div class="row">
										<section class="col col-8 flexibled-error">
											<label class="label">
												Title

												@if($errors->has('title'))
													<div class="error-badge" id="for-title">
														{!! Helper::alert('danger', $errors->first('title')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="title" value="{{ old('title') }}" class="input-sm border-0 border-bottom-1">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Term group

												@if($errors->has('term_group'))
													<div class="error-badge" id="for-term_group">
														{!! Helper::alert('danger', $errors->first('term_group')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="term_group" value="{{ old('term_group') }}"
													class="input-sm border-0 border-bottom-1" placeholder="#number only">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Parent <code>#Optional</code>

												@if($errors->has('parent'))
													<div class="error-badge" id="for-parent">
														{!! Helper::alert('danger', $errors->first('parent')) !!}
													</div>
												@endif
											</label>
											<label class="select">
												<select class="input-sm border-0 border-bottom-1" name="parent">

													{!! Helper::empty_option() !!}

													@foreach($terms as $term)

														@if(old('parent') ==$term->term_id)
															<option value="{{ $term->term_id }}" selected>{{ $term->title }}</option>
														@else
															<option value="{{ $term->term_id }}">{{ $term->title }}</option>
														@endif
													@endforeach
												</select><i></i>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6">
											<label class="label">
												Description
											</label>
											<label class="textarea">
												<textarea name="description" rows="3"
													class="custom-scroll border-0 border-bottom-1">{{ old('description') }}</textarea>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6" data-last="0">
											<label class="input">
												<a href="javascript:;" class="btn btn-link font-bold txt-color-red" id="new_meta">
													<i class="glyphicon glyphicon-share-alt"></i>
													Add meta
												</a>
											</label>
										</section>
									</div>

								</fieldset>

								<footer>
									{{ csrf_field() }}
									<button type="submit" class="btn btn-primary">
										{{ $layout->label->save->title }}
									</button>
									<button type="submit" name="sane" value="true" class="btn btn-default">
										{{ $layout->label->sane->title }}
									</button>
								</footer>
							</form>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

resources/views/content_terms/edit.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->content_terms->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-8">
							
							<form action="{{ route('content_terms.update', encrypt($term->term_id)) }}" class="smart-form" method="post">

								<fieldset>

									<div class="row">
										@if(Session::has('updated'))
											<section class="col col-6">
												{!! Helper::alert('success', Session::get('updated'), 'block font-15') !!}
											</section>
										@endif
									</div>

									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Taxonomy <code>*</code>

												@if($errors->has('taxonomy'))
													<div class="error-badge" id="for-taxonomy">
														{!! Helper::alert('danger', $errors->first('taxonomy')) !!}
													</div>
												@endif
											</label>
											<label class="select">
												<select class="input-sm border-0 border-bottom-1" name="taxonomy">

													{!! Helper::empty_option() !!}

													@foreach($taxonomies as $taxonomy)

														@if($tt->taxonomy ==$taxonomy->taxonomy)
															<option value="{{ $taxonomy->taxonomy }}" selected>{{ $taxonomy->taxonomy }}</option>
														@else
															<option value="{{ $taxonomy->taxonomy }}">{{ $taxonomy->taxonomy }}</option>
														@endif
													@endforeach
												</select><i></i>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Slug

												@if($errors->has('slug'))
													<div class="error-badge" id="for-slug">
														{!! Helper::alert('danger', $errors->first('slug')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="slug" value="{{ !old('slug') ? $term->slug :old('slug') }}" class="input-sm border-0 border-bottom-1">
											</label>
											<div class="note">
												{!! $layout->label->slug_note->title !!}
											</div>
										</section>
									</div>
									<div class="row">
										<section class="col col-8 flexibled-error">
											<label class="label">
												Title

												@if($errors->has('title'))
													<div class="error-badge" id="for-title">
														{!! Helper::alert('danger', $errors->first('title')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="title" value="{{ !old('title') ? $term->title :old('title') }}" class="input-sm border-0 border-bottom-1">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Term group

												@if($errors->has('term_group'))
													<div class="error-badge" id="for-term_group">
														{!! Helper::alert('danger', $errors->first('term_group')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="term_group" value="{{ !old('term_group') ? $term->term_group :old('term_group') }}" 
													class="input-sm border-0 border-bottom-1" placeholder="#number only">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Parent <code>#Optional</code>

												@if($errors->has('parent'))
													<div class="error-badge" id="for-parent">
														{!! Helper::alert('danger', $errors->first('parent')) !!}
													</div>
												@endif
											</label>
											<label class="select">
												<select class="input-sm border-0 border-bottom-1" name="parent">

													{!! Helper::empty_option() !!}

													@foreach($terms as $term)

														@if($tt->parent ==$term->term_id)
															<option value="{{ $term->term_id }}" selected>{{ $term->title }}</option>
														@else
															<option value="{{ $term->term_id }}">{{ $term->title }}</option>
														@endif
													@endforeach
												</select><i></i>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6">
											<label class="label">
												Description
											</label>
											<label class="textarea">
												<textarea name="description" rows="3"
													class="custom-scroll border-0 border-bottom-1">{{ $tt->description }}</textarea>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6" data-last="0">
											<label class="input">
												<a href="javascript:;" class="btn btn-link font-bold txt-color-red" id="new_meta">
													<i class="glyphicon glyphicon-share-alt"></i>
													Add meta
												</a>
											</label>
										</section>
									</div>

									{!! $str_meta !!}

								</fieldset>

								<footer>
									{{ method_field('put') }}
									{{ csrf_field() }}
									<button type="submit" class="btn btn-primary">
										{{ $layout->label->save->title }}
									</button>
								</footer>
							</form>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

resources/views/content_terms/index.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->content_terms->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-12">

							@if(Session::has('deleted'))
								<section>
									{!! Helper::alert('success', Session::get('deleted'), 'block font-15') !!}
								</section>
							@endif
							
							<div class="table-responsive">

								<table class="table table-hover">
									<thead>
										<tr>
											<th>#</th>
											<th>Id</th>
											<th>Parent</th>
											<th>Taxonomy</th>
											<th>Slug</th>
											<th>Title</th>
											<th>Term group</th>
											<th>Module</th>
										</tr>
									</thead>
									<tbody>
										@if(count($content_terms) ==0)
											{!! Helper::empty_table(7) !!}
										@endif

										@foreach($content_terms as $key => $content_term)
									      	<tr>
										        <td>{{ \Helper::indexed($content_terms, $key) }}</td>
										        <td>
										        	<code>
										        		{{ $content_term->term_id }}
										        	</code>
											        <a id="p{{ $content_term->term_id }}" class="hyper"></a>
										        </td>
										        <td>
										        	<a href="#p{{ $content_term->parent }}">
										        		{{ $content_term->parent }}
										        	</a>
										        </td>
										        <td>
										        	<span class="font-12 txt-color-blue">
										        		{{ $content_term->taxonomy }}
										        	</span>
										        </td>
										        <td>
										        	<code>
										        		{{ $content_term->slug }}
										        	</code>
										        </td>
										        <td>
										        	<div class="truncate-475" title="{{ $content_term->title }}">
										        		{!! $content_term->title !!}
										        	</div>
										        </td>
										        <td>{{ $content_term->term_group }}</td>
										        <td>
										        	<div class="btn-action">
											        	<a href="{{ route('content_terms.edit', encrypt($content_term->term_id)) }}" class="btn btn-primary btn-xs">edit</a>
											        	<form action="{{ route('content_terms.destroy', encrypt($content_term->term_id)) }}" method="post" class="inline-block">
															{{ method_field('delete') }}
															{{ csrf_field() }}
															<button type="button" class="btn btn-danger btn-xs jscfm">Delete</button>
														</form>
													</div>
										        </td>
									      	</tr>
										@endforeach
									</tbody>
								</table>

							</div>
							<!-- End + div.table-responsive -->

							<div class="table-footer">

								{!! \Helper::paginator(['route' => 'content_terms'], ['items' => $content_terms], ['display' => $display]) !!}

							</div>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection