routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('posts', 'PostsController');

Route::resource('pages', 'PagesController');

Route::resource('content_terms', 'ContentTermsController', ['except' => ['show']]);

Route::get('languages/{id}/set', ['as' => 'languages.set', 'uses' => 'LanguagesController@set']);
Route::resource('languages', 'LanguagesController', ['except' => ['show']]);

Route::resource('layout_categories', 'LayoutCategoriesController', ['except' => ['show']]);

Route::resource('layout_items', 'LayoutItemsController', ['except' => ['show']]);

Route::get('layout_item_translates/create/{encrypted_id}', ['as' => 'layout_item_translates.create', 'uses' => 'LayoutItemTranslatesController@create']);
Route::resource('layout_item_translates', 'LayoutItemTranslatesController', ['except' => ['create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_roles', 'UserRolesController', ['except' => ['show']]);

Route::get('user_privileges/create/{encrypted_id}', ['as' => 'user_privileges.create', 'uses' => 'UserPrivilegesController@create']);
Route::resource('user_privileges', 'UserPrivilegesController', ['except' => ['create', 'show', 'edit', 'destroy']]);

Route::resource('profiles', 'ProfilesController', ['only' => ['edit', 'update']]);

Route::resource('user_accounts', 'UserAccountsController', ['except' => ['show']]);

Route::resource('user_metas', 'UserMetasController', ['except' => ['index', 'create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_passwords', 'UserPasswordsController', ['only' => ['update']]);

Route::resource('privileges', 'PrivilegesController', ['except' => ['show']]);

// Static Ajax routes ;
Route::prefix('ajax')->group(function () {
	Route::post('of_taxonomy', ['as' => 'ajax.of_taxonomy', 'uses' => 'AjaxController@of_taxonomy']);
	Route::post('realtime_upload', ['as' => 'ajax.realtime_upload', 'uses' => 'AjaxController@realtime_upload']);
});

app/UserAccounts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserAccounts extends Model
{
    //
}

app/Http/Controllers/UserAccountsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use Session;
use File;
use Image;

use App\User;
use App\UserRoles;
use App\Privileges;
use App\UserMetas;
use App\UserAccounts;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Input;

class UserAccountsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->authorized('user_accounts')) {
            abort(403, 'Unauthorized action.');
        }

        $display = Input::has('display') ? Input::get('display') :7;

        $user_accounts = DB::table('users')
                            ->select(
                                'users.id',
                                'user_roles.title as role',
                                'users.email',
                                'users.created_at',
                                'users.updated_at',
                                DB::raw('concat(\'{\', group_concat(\'"\', user_meta.meta_key, \'":"\', user_meta.meta_value, \'"\' ORDER BY user_meta.meta_key ASC), \'}\') as obj')
                            )
                            ->join('user_roles', 'users.role_id', '=', 'user_roles.id')
                            ->leftJoin('user_meta', 'users.id', '=', 'user_meta.user_id')
                            ->groupBy('users.id')
                            ->orderBy('users.created_at', 'desc')
                            ->paginate($display);

        // decode obj json ___
        $users = array();

        foreach ($user_accounts as $key => $value)
        {

            $usr = json_decode($value->obj);

            $key = (object) array(
                        'id' => $value->id,
                        'role' => $value->role,
                        'name' => $usr->name,
                        'email' => $value->email,
                        'phone' => $usr->phone,
                        'created_at' => $value->created_at,
                        'updated_at' => $value->updated_at
                    );

            array_push($users, $key);
        }

        return view('user_accounts.index', compact(['user_accounts', 'users', 'display']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(!Auth::user()->authorized('create_user_account')) {
            abort(403, 'Unauthorized action.');
        }

        $user_roles = UserRoles::all();

        return view('user_accounts.create', compact('user_roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!Auth::user()->authorized('create_user_account')) {
            abort(403, 'Unauthorized action.');
        }

        $validator = Validator::make($request->all(), [
                'role_id' => 'required|numeric',
                'profile' => 'image|mimes:jpg,jpeg,png,bmp|max:' . (1024 *16),
                'name' => 'required',
                'phone' => 'nullable|regex:/^(?=.*[0-9])[- +()0-9]+$/',
                'email' => 'required|max:64|unique:users',
                'password' => 'required|min:6|confirmed',
            ]);

        if($validator->fails())
        {
            return redirect()->back()
                    ->withInput()
                    ->withErrors($validator);
        }

        // Required - hash password before stored
        $request->merge(['password' => Hash::make($request->input('password'))]);

        // decrypted role_id, cause encrypted at frontend
        $user = new User([
                'role_id' => $request->input('role_id'),
                'email' => $request->input('email'),
                'password' => $request->input('password'),
            ]);

        $user->save();

        // store user meta if inputed ____
        $default = array('profile', 'name', 'phone');

        foreach ($request->all() as $key => $value)
        {
            if(in_array($key, $default))
            {
                $valued = $value;

                if($key =='profile')
                {
                    // store profile ;
                    $request->profile->store($user->id, 'public');

                    $profile_dir = storage_path('app/public/'. $user->id .'/profile');

                    if(!File::exists($profile_dir))
                    {
                        File::makeDirectory($profile_dir);
                    }

                    Image::make($request->profile->getRealPath())->fit(120)->save($profile_dir .'/'. $request->profile->hashName());

                    $valued = $request->profile->hashName();
                }

                $user_meta = new UserMetas([
                        'user_id' => $user->id,
                        'meta_key' => $key,
                        'meta_value' => $valued
                    ]);

                $user_meta->save();
            }
        }

        return redirect('user_accounts');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\UserAccounts  $userAccounts
     * @return \Illuminate\Http\Response
     */
    public function edit($encrypted_id)
    {
        if(!Auth::user()->authorized('update_user_account')) {
            abort(403, 'Unauthorized action.');
        }

        $user_roles = UserRoles::all();

        $decrypted_id = decrypt($encrypted_id);

        $user_meta = \Helper::metas('user_meta', ['user_id' => $decrypted_id]);

        $profile = isset($user_meta->profile) ? Storage::url($decrypted_id .'/profile/'. $user_meta->profile->value) : '/assets/admin/img/avatars/male.png';

        $user = User::select('id', 'role_id', 'email', 'created_at')->where('id', $decrypted_id)->first();

        return view('user_accounts.edit', compact(['user_roles', 'user', 'user_meta', 'profile']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\UserAccounts  $userAccounts
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $encrypted_id)
    {
        if(!Auth::user()->authorized('update_user_account')) {
            abort(403, 'Unauthorized action.');
        }

        $decrypted_id = decrypt($encrypted_id);

        $validator = Validator::make($request->all(), [
                'role_id' => 'required|numeric',
                'profile' => 'image|mimes:jpg,jpeg,png,bmp|max:' . (1024 *16),
                'name' => 'required',
                'phone' => 'nullable|regex:/^(?=.*[0-9])[- +()0-9]+$/',
            ]);

        if($validator->fails()) {
            return redirect()->back()
                    ->withInput()
                    ->withErrors($validator);
        }

        // update role __
        $user = User::find($decrypted_id);
        $user->role_id = $request->input('role_id');
        $user->save();

        // update metas +
        $meta = array(
                'name' => $request->input('name'),
                'phone' => $request->input('phone')
            );
        $excepts = ['profile'];

        if($request->file('profile') !=null)
        {
            $request->profile->store($decrypted_id, 'public');

            $profile_dir = storage_path('app/public/'. $decrypted_id .'/profile');

            if(!File::exists($profile_dir))
            {
                File::makeDirectory($profile_dir);
            }

            // store fit profile ;
            Image::make($request->profile->getRealPath())->fit(120)->save($profile_dir .'/'. $request->profile->hashName());

            $meta['profile'] = $request->profile->hashName();

            $excepts =[];
        }

        \Helper::store_meta('user_meta', ['user_id' => $decrypted_id], $meta, $excepts, false);

        Session::flash('updated', 'User profile is updated');

        return redirect()->route('user_accounts.edit', $encrypted_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\UserAccounts  $userAccounts
     * @return \Illuminate\Http\Response
     */
    public function destroy($encrypted_id)
    {
        if(!Auth::user()->authorized('delete_user_account')) {
            abort(403, 'Unauthorized action.');
        }

        $decrypted_id = decrypt($encrypted_id);

        $user = DB::table('users')->where('id', $decrypted_id)->limit(1);
        $user->delete();

        $user_meta = UserMetas::where('user_id', $decrypted_id);
        $user_meta->delete();

        Session::flash('deleted', "User is deleted");

        return redirect('user_accounts');
    }
}

resources/views/user_accounts/create.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->create_user_account->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-8">

							<form action="{{ route('user_accounts.index') }}" class="smart-form" method="post" enctype="multipart/form-data">

								<fieldset>

									<div class="row">
										@if(Session::has('inserted'))
											<section class="col col-6">
												{!! Helper::alert('success', Session::get('inserted'), 'block font-15') !!}
											</section>
										@endif
									</div>

									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Role <code>*</code>

												@if($errors->has('role_id'))
													<div class="error-badge" id="for-role_id">
														{!! Helper::alert('danger', $errors->first('role_id')) !!}
													</div>
												@endif
											</label>
											<label class="select">
												<select class="input-sm border-0 border-bottom-1" name="role_id">

													{!! Helper::empty_option() !!}

													@foreach($user_roles as $user_role)

														@if(old('role_id') ==$user_role->id)
															<option value="{{ $user_role->id }}" selected>{{ $user_role->title }}</option>
														@else
															<option value="{{ $user_role->id }}">{{ $user_role->title }}</option>
														@endif
													@endforeach
												</select><i></i>
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Profile

												@if($errors->has('profile'))
													<div class="error-badge" id="for-profile">
														{!! Helper::alert('danger', $errors->first('profile')) !!}
													</div>
												@endif
											</label>
											<div class="input input-file">
												<span class="button">
													<input type="file" name="profile" accept="image/*" onchange="this.parentNode.nextSibling.value = this.value">
														Browse
												</span><input type="text" class="border-0 border-bottom-1" placeholder="Include some files" readonly="">
											</div>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Name

												@if($errors->has('name'))
													<div class="error-badge" id="for-name">
														{!! Helper::alert('danger', $errors->first('name')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="name" value="{{ old('name') }}" class="input-sm border-0 border-bottom-1">
											</label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Phone

												@if($errors->has('phone'))
													<div class="error-badge" id="for-phone">
														{!! Helper::alert('danger', $errors->first('phone')) !!}
													</div>
												@endif
											</label>
											<label class="input">
												<input type="text" name="phone" value="{{ old('phone') }}" class="input-sm border-0 border-bottom-1">
											</label>
											<div class="note">
												{!! $layout->label->phone_note->title !!}
											</div>
										</section>
									</div>

								</fieldset>

								<fieldset>

									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Email

												@if($errors->has('email'))
													<div class="error-badge" id="for-email">
														{!! Helper::alert('danger', $errors->first('email')) !!}
													</div>
												@endif
											</label>
											<label class="input"> <i class="icon-append fa fa-envelope"></i>
												<input type="email" name="email" value="{{ old('email') }}" class="border-0 border-bottom-1"></label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Password

												@if($errors->has('password'))
													<div class="error-badge" id="for-password">
														{!! Helper::alert('danger', $errors->first('password')) !!}
													</div>
												@endif
											</label>
											<label class="input"> <i class="icon-append fa fa-lock"></i>
												<input type="password" name="password" class="border-0 border-bottom-1"></label>
										</section>
									</div>
									<div class="row">
										<section class="col col-6 flexibled-error">
											<label class="label">
												Confirm password </label>

											<label class="input"> <i class="icon-append fa fa-undo"></i>
												<input type="password" name="password_confirmation" class="border-0 border-bottom-1"></label>
										</section>
									</div>

								</fieldset>

								<footer>
									{{ csrf_field() }}
									<button type="submit" class="btn btn-primary">
										{{ $layout->label->save->title }}
									</button>
								</footer>
							</form>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

resources/views/user_accounts/edit.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->user_accounts->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-8">

							<ul class="nav nav-tabs">
								<li class="{{ !Session::has('password') ? 'active' :'' }}">
									<a href="#personal" data-toggle="tab">
										<i class="glyphicon glyphicon-user"></i> Personal info</a>
								</li>
								<li class="{{ Session::has('password') ? 'active' :'' }}">
									<a href="#credential" data-toggle="tab">
										<i class="glyphicon glyphicon-lock"></i> Password</a>
								</li>
							</ul>

							<div class="tab-content">

								<div class="tab-pane fade in {{ !Session::has('password') ? 'active' :'' }}" id="personal">

									<form action="{{ route('user_accounts.update', encrypt($user->id)) }}" class="smart-form" method="post" enctype="multipart/form-data">

										<fieldset>

											<div class="row">
												@if(Session::has('updated'))
													<section class="col col-6">
														{!! Helper::alert('success', Session::get('updated'), 'block font-15') !!}
													</section>
												@endif
											</div>

											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Role <code>[ #important ]</code>

														@if($errors->has('role_id'))
															<div class="error-badge" id="for-role_id">
																{!! Helper::alert('danger', $errors->first('role_id')) !!}
															</div>
														@endif
													</label>
													<label class="select">
														<select class="input-sm border-0 border-bottom-1" name="role_id">

															{!! Helper::empty_option() !!}

															@foreach($user_roles as $user_role)
																@if($user->role_id == $user_role->id)
																	<option value="{{ $user_role->id }}" selected>{{ $user_role->title }}</option>
																@else
																	<option value="{{ $user_role->id }}">{{ $user_role->title }}</option>
																@endif
															@endforeach
														</select><i></i>
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-4 pull-right">
													<div class="profile-alt height-0">
														<img src="{{ $profile }}" width="112" height="112" alt=".profile" />
													</div>
													<div class="profile-note">
														<code>#Profile</code>
													</div>
												</section>
												<section class="col col-6 flexibled-error">
													<label class="label">
														Change profile ?

														@if($errors->has('profile'))
															<div class="error-badge" id="for-profile">
																{!! Helper::alert('danger', $errors->first('profile')) !!}
															</div>
														@endif
													</label>
													<div class="input input-file">
														<span class="button">
															<input type="file" name="profile" accept="image/*" onchange="this.parentNode.nextSibling.value = this.value">
																Browse
														</span><input type="text" class="border-0 border-bottom-1" placeholder="Include some files" readonly="">
													</div>
												</section>
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Name

														@if($errors->has('name'))
															<div class="error-badge" id="for-name">
																{!! Helper::alert('danger', $errors->first('name')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="name" value="{{ old('name') ? old('name') :$user_meta->name->value }}" class="input-sm border-0 border-bottom-1">
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Phone

														@if($errors->has('phone'))
															<div class="error-badge" id="for-phone">
																{!! Helper::alert('danger', $errors->first('phone')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="phone" value="{{ old('phone') ? old('phone') :$user_meta->phone->value }}" class="input-sm border-0 border-bottom-1">
													</label>
													<div class="note">
														{!! $layout->label->phone_note->title !!}
													</div>
												</section>
											</div>

										</fieldset>

										<footer>
											{{ method_field('put') }}
											{{ csrf_field() }}
											<button type="submit" class="btn btn-primary">
												{{ $layout->label->save->title }}
											</button>
										</footer>
									</form>

								</div>

								<div class="tab-pane fade in {{ Session::has('password') ? 'active' :'' }}" id="credential">

									<form action="{{ route('user_passwords.update', encrypt($user->id)) }}" class="smart-form" method="post">

										<fieldset>

											<div class="row">
											@if(Session::has('updated'))
												<section class="col col-6">
													{!! Helper::alert('success', Session::get('updated'), 'block font-15') !!}
												</section>
											@endif
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Email <code>#not required</code>
													</label>
													<label class="input"> <i class="icon-append fa fa-envelope"></i>
														<input type="email" value="{{ $user->email }}" class="font-18 border-0 border-bottom-1" disabled></label>
												</section>
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Current Password

														@if($errors->has('curr_password'))
															<div class="error-badge" id="for-curr_password">
																{!! Helper::alert('danger', $errors->first('curr_password')) !!}
															</div>
														@endif
													</label>
													<label class="input"> <i class="icon-append fa fa-code"></i>
														<input type="password" name="curr_password" value="{{ old('curr_password') }}" class="border-0 border-bottom-1"></label>
												</section>
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Password

														@if($errors->has('password'))
															<div class="error-badge" id="for-password">
																{!! Helper::alert('danger', $errors->first('password')) !!}
															</div>
														@endif
													</label>
													<label class="input"> <i class="icon-append fa fa-lock"></i>
														<input type="password" name="password" value="{{ old('password') }}" class="border-0 border-bottom-1"></label>
												</section>
											</div>
											<div class="row">
												<section class="col col-6 flexibled-error">
													<label class="label">
														Confirm password </label>
													<label class="input"> <i class="icon-append fa fa-undo"></i>
														<input type="password" name="password_confirmation" value="{{ old('password_confirmation') }}" class="border-0 border-bottom-1"></label>
												</section>
											</div>

										</fieldset>

										<footer>
											{{ method_field('put') }}
											{{ csrf_field() }}
											<button type="submit" class="btn btn-primary">
												{{ $layout->label->save->title }}
											</button>
										</footer>
									</form>

								</div>
							</div>
							<!-- End div.tab-content -->

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

resources/views/user_accounts/index.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->user_accounts->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-12">							

							@if(Session::has('deleted'))
								<section>
									{!! Helper::alert('success', Session::get('deleted'), 'block font-15') !!}
								</section>
							@endif

							<div class="table-responsive">

								<table class="table table-hover">
									<thead>
										<tr>
											<th>#</th>
											<th>Role as</th>
											<th>Name</th>
											<th>Email</th>
											<th>#tel</th>
											<th>Created at</th>
											<th>Updated at</th>
											<th>Module</th>
										</tr>
									</thead>
									<tbody>
										@if(count($users) ==0)
											{!! Helper::empty_table(8) !!}
										@endif

										@foreach($users as $key => $user)
									      	<tr>
										        <td>{{ \Helper::indexed($user_accounts, $key) }}</td>
										        <td>
										        	<code>{{ $user->role }}</code>
										        </td>
										        <td>{{ $user->name }}</td>
										        <td>{!! $user->email !!}</td>
										        <td>{{ $user->phone }}</td>
										        <td>{{ $user->created_at }}</td>
										        <td>{{ $user->updated_at }}</td>
										        <td>
										        	<div class="btn-action">
											        	<a href="{{ route('user_accounts.edit', encrypt($user->id)) }}" class="btn btn-primary btn-xs">edit</a>
											        	<form action="{{ route('user_accounts.destroy', encrypt($user->id)) }}" method="post" class="inline-block">
															{{ method_field('delete') }}
															{{ csrf_field() }}
															<button type="button" class="btn btn-danger btn-xs jscfm">Delete</button>
														</form>
													</div>
										        </td>
									      	</tr>
										@endforeach
									</tbody>
								</table>

							</div>
							<!-- End + div.table-responsive -->

							<div class="table-footer">
								
								{!! \Helper::paginator(['route' => 'user_accounts'], ['items' => $user_accounts], ['display' => $display]) !!}

							</div>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection