routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::resource('posts', 'PostsController');

Route::resource('pages', 'PagesController');

Route::resource('content_terms', 'ContentTermsController', ['except' => ['show']]);

Route::get('languages/{id}/set', ['as' => 'languages.set', 'uses' => 'LanguagesController@set']);
Route::resource('languages', 'LanguagesController', ['except' => ['show']]);

Route::resource('layout_categories', 'LayoutCategoriesController', ['except' => ['show']]);

Route::resource('layout_items', 'LayoutItemsController', ['except' => ['show']]);

Route::get('layout_item_translates/create/{encrypted_id}', ['as' => 'layout_item_translates.create', 'uses' => 'LayoutItemTranslatesController@create']);
Route::resource('layout_item_translates', 'LayoutItemTranslatesController', ['except' => ['create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_roles', 'UserRolesController', ['except' => ['show']]);

Route::get('user_privileges/create/{encrypted_id}', ['as' => 'user_privileges.create', 'uses' => 'UserPrivilegesController@create']);
Route::resource('user_privileges', 'UserPrivilegesController', ['except' => ['create', 'show', 'edit', 'destroy']]);

Route::resource('profiles', 'ProfilesController', ['only' => ['edit', 'update']]);

Route::resource('user_accounts', 'UserAccountsController', ['except' => ['show']]);

Route::resource('user_metas', 'UserMetasController', ['except' => ['index', 'create', 'show', 'edit', 'update', 'destroy']]);

Route::resource('user_passwords', 'UserPasswordsController', ['only' => ['update']]);

Route::resource('privileges', 'PrivilegesController', ['except' => ['show']]);

// Static Ajax routes ;
Route::prefix('ajax')->group(function () {
	Route::post('of_taxonomy', ['as' => 'ajax.of_taxonomy', 'uses' => 'AjaxController@of_taxonomy']);
	Route::post('realtime_upload', ['as' => 'ajax.realtime_upload', 'uses' => 'AjaxController@realtime_upload']);
});

resources/views/pages/create.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->create_page->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-12">

							<form action="{{ route('pages.index') }}" class="smart-form" method="post">

								<fieldset>

									<div class="row">
										@if(Session::has('inserted'))
											<section class="col col-8">
												{!! Helper::alert('success', Session::get('inserted'), 'block font-15') !!}
											</section>
										@endif
									</div>

									<div class="row">
										
										<section class="col col-8">
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Title <code>*</code>

														@if($errors->has('title'))
															<div class="error-badge" id="for-title">
																{!! Helper::alert('danger', $errors->first('title')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="title" value="{{ old('title') }}" class="input-sm border-0 border-bottom-1 font-bold font-18">
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error atoslug-upper">
													<label class="label">
														Slug <code>*</code> <botton class="btn btn-xs btn-primary atoslug" data-target="slug" data-slugof="page">auto</botton>

														@if($errors->has('slug'))
															<div class="error-badge" id="for-slug">
																{!! Helper::alert('danger', $errors->first('slug')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="slug" value="{{ old('slug') }}" class="input-sm border-0 border-bottom-1 font-15">
													</label>
													<div class="note">
														{!! $layout->label->slug_note->title !!}
													</div>
												</section>
											</div>
											<div class="row">
												<section class="col col-10">
													<label class="label">
														Excerpt
													</label>
													<label class="textarea">
														<textarea name="excerpt" rows="3" data-height="75" data-menubar="false" data-ignore="image"
															id="excerpt" class="custom-scroll tinymce border-0 border-bottom-1">{{ old('excerpt') }}</textarea>
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Description <code>*</code>

														@if($errors->has('description'))
															<div class="error-badge" id="for-description">
																{!! Helper::alert('danger', $errors->first('description')) !!}
															</div>
														@endif
													</label>
													<label class="textarea">
														<textarea name="description" rows="7"
															id="description" class="custom-scroll tinymce border-0 border-bottom-1">{{ old('description') }}</textarea>
													</label>
												</section>
											</div>	
										</section>

										<section class="col col-4">
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Language <code>*</code>

														@if($errors->has('language_id'))
															<div class="error-badge" id="for-language_id">
																{!! Helper::alert('danger', $errors->first('language_id')) !!}
															</div>
														@endif
													</label>
													<label class="select">
														<select class="input-sm border-0 border-bottom-1" name="language_id">

															{!! Helper::empty_option() !!}

															@foreach($languages as $language)

																@if(old('language_id') ==$language->id || !old('language_id') && $language->slug =='en')
																	<option value="{{ $language->id }}" selected>{{ $language->title }}</option>
																@else
																	<option value="{{ $language->id }}">{{ $language->title }}</option>
																@endif
															@endforeach

														</select><i></i>
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Translate of

														@if($errors->has('translate_of'))
															<div class="error-badge" id="for-translate_of">
																{!! Helper::alert('danger', $errors->first('translate_of')) !!}
															</div>
														@endif
													</label>
													<label class="select">
														<select class="input-sm border-0 border-bottom-1" name="translate_of">

															{!! Helper::empty_option() !!}

															@foreach($ofpages as $ofpage)

																@if(old('translate_of') ==$ofpage->id)
																	<option value="{{ $ofpage->id }}" selected>{{ $ofpage->title }}</option>
																@else
																	<option value="{{ $ofpage->id }}">{{ $ofpage->title }}</option>
																@endif
															@endforeach

														</select><i></i>
													</label>
												</section>
											</div>												
										</section>

									</div>

								</fieldset>

								<footer>
									{{ csrf_field() }}
									<button type="submit" class="btn btn-primary">
										{{ $layout->label->save->title }}
									</button>
									<button type="submit" name="sane" value="true" class="btn btn-default">
										{{ $layout->label->sane->title }}
									</button>
								</footer>
							</form>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

@section('script')
	<script src="{{ asset('assets/admin/js/libs/tinymce/tinymce.min.js') }}"></script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->pages->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-12">

							<form action="{{ route('pages.update', encrypt($page->id)) }}" class="smart-form" method="post">

								<fieldset>

									<div class="row">
										@if(Session::has('updated'))
											<section class="col col-8">
												{!! Helper::alert('success', Session::get('updated'), 'block font-15') !!}
											</section>
										@endif
									</div>

									<div class="row">

										<section class="col col-8">
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Title <code>*</code>

														@if($errors->has('title'))
															<div class="error-badge" id="for-title">
																{!! Helper::alert('danger', $errors->first('title')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="title" value="{{ old('title') ? old('title') : $page->title }}" class="input-sm border-0 border-bottom-1 font-bold font-18">
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error atoslug-upper">
													<label class="label">
														Slug <code>*</code> <botton class="btn btn-xs btn-primary atoslug" data-target="slug" data-slugof="page">auto</botton>

														@if($errors->has('slug'))
															<div class="error-badge" id="for-slug">
																{!! Helper::alert('danger', $errors->first('slug')) !!}
															</div>
														@endif
													</label>
													<label class="input">
														<input type="text" name="slug" value="{{ old('slug') ? old('slug') :$page->slug }}" class="input-sm border-0 border-bottom-1 font-15">
													</label>
													<div class="note">
														{!! $layout->label->slug_note->title !!}
													</div>
												</section>
											</div>
											<div class="row">
												<section class="col col-10">
													<label class="label">
														Excerpt
													</label>
													<label class="textarea">
														<textarea name="excerpt" rows="3" data-height="75" data-menubar="false" data-ignore="image"
															id="excerpt" class="custom-scroll tinymce border-0 border-bottom-1">{{ old('excerpt') ? old('excerpt') :$page->excerpt }}</textarea>
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Description <code>*</code>

														@if($errors->has('description'))
															<div class="error-badge" id="for-description">
																{!! Helper::alert('danger', $errors->first('description')) !!}
															</div>
														@endif
													</label>
													<label class="textarea">
														<textarea name="description" rows="7"
															id="description" class="custom-scroll tinymce border-0 border-bottom-1">{{ old('description') ? old('description') :$page->description }}</textarea>
													</label>
												</section>
											</div>
										</section>

										<section class="col col-4">
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Language <code>*</code>

														@if($errors->has('language_id'))
															<div class="error-badge" id="for-language_id">
																{!! Helper::alert('danger', $errors->first('language_id')) !!}
															</div>
														@endif
													</label>
													<label class="select">
														<select class="input-sm border-0 border-bottom-1" name="language_id">

															{!! Helper::empty_option() !!}

															@foreach($languages as $language)

																@if(old('language_id') ==$language->id || !old('language_id') && $page->language_id ==$language->id)
																	<option value="{{ $language->id }}" selected>{{ $language->title }}</option>
																@else
																	<option value="{{ $language->id }}">{{ $language->title }}</option>
																@endif
															@endforeach

														</select><i></i>
													</label>
												</section>
											</div>
											<div class="row">
												<section class="col col-10 flexibled-error">
													<label class="label">
														Translate of

														@if($errors->has('translate_of'))
															<div class="error-badge" id="for-translate_of">
																{!! Helper::alert('danger', $errors->first('translate_of')) !!}
															</div>
														@endif
													</label>
													<label class="select">
														<select class="input-sm border-0 border-bottom-1" name="translate_of">

															{!! Helper::empty_option() !!}

															@foreach($ofpages as $ofpage)

																@if(old('translate_of') ==$ofpage->id || !old('translate_of') && $page->translate_of == $ofpage->id)
																	<option value="{{ $ofpage->id }}" selected>{{ $ofpage->title }}</option>
																@else
																	<option value="{{ $ofpage->id }}">{{ $ofpage->title }}</option>
																@endif
															@endforeach

														</select><i></i>
													</label>
												</section>
											</div>
										</section>
										
									</div>

								</fieldset>

								<footer>
									{{ method_field('put') }}
									{{ csrf_field() }}
									<button type="submit" class="btn btn-primary">
										{!! $layout->label->save->title !!}
									</button>
								</footer>
							</form>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection

@section('script')
	<script src="{{ asset('assets/admin/js/libs/tinymce/tinymce.min.js') }}"></script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.admin.master')

@section('content')
	<div id="content">

		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
				<h1 class="page-title txt-color-blueDark">
					{{ $layout->menu->pages->title }}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">

				<div class="well well-sm">

					<div class="row">
						<div class="col-md-12 col-lg-12">

							@if(Session::has('deleted'))
								<section>
									{!! Helper::alert('success', Session::get('deleted'), 'block font-15') !!}
								</section>
							@endif
							
							<div class="table-responsive">

								<table class="table table-hover">
									<thead>
										<tr>
											<th>#</th>
											<th>Id</th>
											<th>Parent</th>
											<th>Tslt of</th>
											<th>Slug</th>
											<th>Title</th>
											<th>Viewed</th>
											<th>Shared</th>
											<th>Favorited</th>
											<th>Module</th>
										</tr>
									</thead>
									<tbody>
										@if(count($pages) ==0)
											{!! Helper::empty_table(10) !!}
										@endif

										@foreach($pages as $key => $page)
									      	<tr>
										        <td>{{ \Helper::indexed($pages, $key) }}</td>
										        <td>
										        	<code>
										        		{{ $page->id }}
										        	</code>
											        <a id="p{{ $page->id }}" class="hyper"></a>
										        </td>
										        <td>
										        	<a href="#p{{ $page->content_parent }}">
										        		{{ $page->content_parent }}
										        	</a>
										        </td>
										        <td>
										        	<a href="#p{{ $page->translate_of }}">
											        	<span class="font-12 txt-color-blue">
											        		{{ $page->translate_of }}
											        	</span>
											        </a>
										        </td>
										        <td>
										        	<code>
										        		{{ $page->slug }}
										        	</code>
										        </td>
										        <td>
										        	<div class="truncate-475" title="{{ $page->title }}">
										        		{!! $page->title !!}
										        	</div>
										        </td>
										        <td>{{ $page->viewed }}</td>
										        <td>{{ $page->shared }}</td>
										        <td>{{ $page->favorited }}</td>
										        <td>
										        	<div class="btn-action">
											        	<a href="{{ route('pages.edit', encrypt($page->id)) }}" class="btn btn-primary btn-xs">edit</a>
											        	<form action="{{ route('pages.destroy', encrypt($page->id)) }}" method="post" class="inline-block">
															{{ method_field('delete') }}
															{{ csrf_field() }}
															<button type="button" class="btn btn-danger btn-xs jscfm">Delete</button>
														</form>
													</div>
										        </td>
									      	</tr>
										@endforeach
									</tbody>
								</table>

							</div>
							<!-- End + div.table-responsive -->

							<div class="table-footer">

								{!! \Helper::paginator(['route' => 'pages'], ['items' => $pages], ['display' => $display]) !!}

							</div>

						</div>
					</div>
					<!-- End div.row +child -->

				</div>
				<!-- End .well class -->

			</div>
		</div>
		<!-- End div.row +parent -->

	</div>
	<!-- END MAIN CONTENT -->

@endsection